# Generated by Django 5.1.2 on 2024-10-19 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0003_remove_wishlistitem_price_wishlistitem_max_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlistitem',
            name='store_address',
        ),
    ]
