# Generated by Django 5.1.2 on 2024-10-22 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_remove_productentry_product_dataset_and_more'),
        ('user_profile', '0006_alter_buyerprofile_user_alter_sellerprofile_user'),
        ('wishlist', '0004_remove_wishlistitem_store_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlistitem',
            name='user',
        ),
        migrations.AddField(
            model_name='wishlistitem',
            name='buyers',
            field=models.ManyToManyField(related_name='wishlist_items', to='user_profile.buyerprofile'),
        ),
        migrations.AddField(
            model_name='wishlistitem',
            name='products',
            field=models.ManyToManyField(related_name='wishlist_products', to='seller.productentry'),
        ),
    ]
