# Generated by Django 5.1.2 on 2024-10-22 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0005_remove_wishlistitem_user_wishlistitem_buyers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlistitem',
            old_name='buyers',
            new_name='user',
        ),
    ]
