# Generated by Django 5.1.2 on 2024-10-23 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0006_alter_buyerprofile_user_alter_sellerprofile_user'),
        ('wishlist', '0007_alter_wishlistitem_products_alter_wishlistitem_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlistitem',
            name='user',
        ),
        migrations.AddField(
            model_name='wishlistitem',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_items', to='user_profile.buyerprofile'),
            preserve_default=False,
        ),
    ]
