# Generated by Django 5.1.2 on 2024-10-23 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0009_remove_wishlistitem_user_wishlistitem_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlistitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
