# Generated by Django 5.1.2 on 2024-10-23 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0010_wishlistitem_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlistitem',
            name='price',
        ),
    ]
