# Generated by Django 5.1.2 on 2024-10-26 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0011_remove_wishlistitem_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlistitem',
            name='max_price',
        ),
        migrations.RemoveField(
            model_name='wishlistitem',
            name='min_price',
        ),
    ]
