# Generated by Django 5.1.2 on 2024-10-22 05:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDataSet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('product_image', models.TextField()),
                ('product_category', models.CharField(choices=[('Textile', 'Textile'), ('Art', 'Art'), ('Handicraft', 'Handicraft'), ('Traditional Wear', 'Traditional Wear'), ('Food', 'Food'), ('Jewelry', 'Jewelry'), ('Souvenir', 'Souvenir'), ('Accessory', 'Accessory'), ('Traditional Weapon', 'Traditional Weapon'), ('Musical Instrument', 'Musical Instrument'), ('Beverage', 'Beverage'), ('Art', 'Art')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ProductEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_name', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('product_image', models.TextField(blank=True, null=True)),
                ('product_category', models.CharField(choices=[('Textile', 'Textile'), ('Art', 'Art'), ('Handicraft', 'Handicraft'), ('Traditional Wear', 'Traditional Wear'), ('Food', 'Food'), ('Jewelry', 'Jewelry'), ('Souvenir', 'Souvenir'), ('Accessory', 'Accessory'), ('Traditional Weapon', 'Traditional Weapon'), ('Musical Instrument', 'Musical Instrument'), ('Beverage', 'Beverage'), ('Art', 'Art')], max_length=255)),
                ('min_price', models.IntegerField()),
                ('max_price', models.IntegerField()),
                ('product_dataset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='seller.productdataset')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSeller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.productentry')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.seller')),
            ],
        ),
    ]
