# Generated by Django 5.1.1 on 2024-10-23 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_remove_productentry_product_dataset_and_more'),
    ]

    operations = [
    ]
