# Generated by Django 5.1.1 on 2024-10-20 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_productentry_product_category_alter_productentry_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productentry',
            name='price',
        ),
    ]
