# Generated by Django 5.1.2 on 2024-10-24 08:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_remove_productentry_product_dataset_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productseller',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
