# Generated by Django 5.1.1 on 2024-10-23 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_auto_20241023_1600'),
    ]

    operations = [
    ]
