# Generated by Django 5.1.2 on 2024-10-24 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_alter_productseller_id'),
        ('seller', '0004_auto_20241023_1603'),
    ]

    operations = [
    ]
