# Generated by Django 5.1.2 on 2024-10-26 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0006_alter_productentry_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productentry',
            name='product_category',
            field=models.CharField(choices=[('Textile', 'Textile'), ('Art', 'Art'), ('Handicraft', 'Handicraft'), ('Traditional Wear', 'Traditional Wear'), ('Food', 'Food'), ('Jewelry', 'Jewelry'), ('Souvenir', 'Souvenir'), ('Accessory', 'Accessory'), ('Traditional Weapon', 'Traditional Weapon'), ('Musical Instrument', 'Musical Instrument'), ('Beverage', 'Beverage')], max_length=255),
        ),
        migrations.AlterField(
            model_name='productseller',
            name='price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
