# Generated by Django 5.1.2 on 2024-10-26 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0007_alter_productentry_product_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productseller',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
