# Generated by Django 5.1.2 on 2024-10-27 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('see_stores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='profile_picture',
            field=models.URLField(blank=True, null=True),
        ),
    ]
