# Generated by Django 5.1.2 on 2024-10-18 06:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleentry',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
