# Generated by Django 5.1.1 on 2024-10-26 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_alter_articleentry_user'),
        ('main', '0003_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleentry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.buyer'),
        ),
    ]
