# Generated by Django 5.1 on 2024-10-22 18:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seller', '0002_remove_productentry_product_dataset_and_more'),
        ('user_profile', '0006_alter_buyerprofile_user_alter_sellerprofile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateField(default=django.utils.timezone.now)),
                ('review_text', models.TextField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.productentry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.buyerprofile')),
            ],
        ),
    ]
