# Generated by Django 5.1.2 on 2024-10-26 14:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_alter_reviewentry_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewentry',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
