# Generated by Django 5.1.1 on 2024-10-26 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seller', '0009_alter_productseller_price'),
        ('user_profile', '0009_alter_buyerprofile_nationality'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.productentry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.buyerprofile')),
            ],
            options={
                'unique_together': {('user', 'product')},
            },
        ),
    ]
