# Generated by Django 5.1.1 on 2024-10-26 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('like', '0001_initial'),
        ('seller', '0009_alter_productseller_price'),
        ('user_profile', '0009_alter_buyerprofile_nationality'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='like',
            name='product',
        ),
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
        migrations.AddField(
            model_name='like',
            name='product',
            field=models.ManyToManyField(to='seller.productentry'),
        ),
        migrations.AddField(
            model_name='like',
            name='user',
            field=models.ManyToManyField(to='user_profile.buyerprofile'),
        ),
    ]
