# Generated by Django 5.1.1 on 2024-10-27 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('like', '0002_alter_like_unique_together_remove_like_product_and_more'),
        ('seller', '0009_alter_productseller_price'),
        ('user_profile', '0009_alter_buyerprofile_nationality'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='product',
        ),
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
        migrations.AddField(
            model_name='like',
            name='product',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='seller.productentry'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='like',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='user_profile.buyerprofile'),
            preserve_default=False,
        ),
    ]
